### PR TITLE
Update performNormalization.R

### PR DESCRIPTION
**Pull request by LinearParadox**
added parallelization to normalize function. This might be memory intensive, but still would offer a speed benefit over a strictly single threaded approach. Under the hood, bpvec splits the vector into the number of workers and then executes the function on them, before joining it back together. 

I tested it against the equivalent single thread method and got an identical result.

### CODE REVIEW

**Comment by ncborcherding** [comment]
Thanks for making a pull request - agreed that the speed for ```performNormalization()``` could be improved substantially. I am working through the testing here (see above) and will get to it this weekend

**Comment by LinearParadox** [comment]
If it passes checks, can we wait a bit to merge? I think the alist suffers on larger datasets with my internal testing, and I have some ideas on how to do it more efficiently after I slept on it. I'll try to push a few commits over the next 2-3 days if that's alright with you? Thank you so much for promptly responding to the push and providing the correction for the important!!

**Comment by ncborcherding** [comment]
Absolutely. It might make things easier if you run `devtools::check()` locally with the updated commit. Also if interested please feel free to add your name to the function (as `@author`) or the package DESCRIPTION. 

Nick

**Comment by LinearParadox** [comment]
The tests seemed to have run locally! I ended up not parallelizing with bpparallel, mostly because it already runs fairly fast since most of it is now vectorized. If someone really wants to, it's fairly easy to just copy the function and change the mapply call to a bpmapply.

**Comment by ncborcherding** [comment]
Hey it looks like the R-CMD-check failed on this one due to mismatch in the new documentation. Would you mind updating the .Rd files on your end with ```devtools::document()```? Then I think we will be golden. 

Thanks so much for your help,
Nick

**Comment by LinearParadox** [comment]
Got it, should be done now. I benchmarked it on my dataset, and it seems like for around 50 gene sets on 9000 cells, runtime is down from around 10 mins to 3 seconds!

**Comment by ncborcherding** [comment]
Looks good to me - thanks for all the help!!

**Pull request merged**
